services:
  redis:
    extends:
      file: docker-compose.deps.yml
      service: redis

  delius:
    extends:
      file: docker-compose.deps.yml
      service: delius

  hmpps-auth:
    extends:
      file: docker-compose.deps.yml
      service: hmpps-auth

  hmpps-auth-proxy:
    extends:
      file: docker-compose.deps.yml
      service: hmpps-auth-proxy

  editor:
    extends:
      file: docker-compose.deps.yml
      service: editor

  app:
    # build:
    #   context: .
    #   args:
    #     BUILD_NUMBER: "1.0.0"
    #     GIT_REF: "a1b2c3"
    #     GIT_BRANCH: main
    #   target: production
    #   network: host  # fixing potential VPN issues.
    #   # 10.12 WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.23/community/aarch64/APKINDEX.tar.gz: DNS: transient error (try again later)
    #   # 10.12 ERROR: Not continuing due to stale/unavailable repositories. Use --force-missing-repositories to continue
    image: "node:22"
    command: sh -c  "npm install && npm run build && npm run start:dev"
    # command: sleep infinity
    user: root # local deployment must be root
    working_dir: "/app"
    networks:
      - hmpps
    depends_on:
      - hmpps-auth-proxy
      - redis
    ports:
      - "3000:3000"
    volumes:
      - node_module:/app/node_modules
      - "./:/app"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000/health"]
    environment:
      - PRODUCT_ID=UNASSIGNED
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9091/auth
      - AUTH_CODE_CLIENT_ID=hmpps-typescript-template
      - AUTH_CODE_CLIENT_SECRET=clientsecret
      - CLIENT_CREDS_CLIENT_ID=hmpps-typescript-template-system
      - CLIENT_CREDS_CLIENT_SECRET=clientsecret
      - SESSION_SECRET=somesecretvalue
      - TOKEN_VERIFICATION_API_URL=http://hmpps-auth:8080/auth
      - TOKEN_VERIFICATION_ENABLED=false
      - INGRESS_URL=http://localhost:3000
      - NO_HTTPS=true
      - NODE_ENV=development

networks:
  hmpps:

volumes:
  node_module:
  content:
