services:
  redis:
    image: "redis:6.2.3-alpine"
    ports:
      - "6379:6379"
    networks:
      - hmpps

  delius:
    image: wiremock/wiremock
    networks:
      - hmpps
    volumes:
      - ./wiremock-delius:/home/wiremock
    command:
      - -verbose
      - -global-response-templating

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:2025-05-02.28494.105ac61
    networks:
      - hmpps
    container_name: hmpps-auth
    depends_on:
      - delius
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,delius
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - DELIUS_ENDPOINT_URL=http://delius:8080
      # - LOGGING_LEVEL_ROOT=INFO
      # - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      # - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=DEBUG

  hmpps-auth-proxy:
    image: nginx:latest
    depends_on:
      - hmpps-auth
    networks:
      - hmpps
    ports:
      - "9091:9091"
    volumes:
      - ./hmpps-auth-proxy/nginx.conf:/etc/nginx/nginx.conf

  app:
    build:
      context: .
      args:
        BUILD_NUMBER: "1.0.0"
        GIT_REF: "a1b2c3"
        GIT_BRANCH: main
      target: production
    command: npm start
    networks:
      - hmpps
    depends_on:
      - hmpps-auth-proxy
      - redis
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000/health"]
    environment:
      - PRODUCT_ID=UNASSIGNED
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9091/auth
      - AUTH_CODE_CLIENT_ID=hmpps-typescript-template
      - AUTH_CODE_CLIENT_SECRET=clientsecret
      - CLIENT_CREDS_CLIENT_ID=hmpps-typescript-template-system
      - CLIENT_CREDS_CLIENT_SECRET=clientsecret
      - SESSION_SECRET=somesecretvalue
      - TOKEN_VERIFICATION_API_URL=http://hmpps-auth:8080/auth
      - TOKEN_VERIFICATION_ENABLED=false
      - INGRESS_URL=http://localhost:3000
      - NO_HTTPS=true
      - NODE_ENV=development

networks:
  hmpps:
