---
# Per environment values which override defaults in hmpps-probation-frontend-component-api/values.yaml

generic-service:
  ingress:
    host: probation-frontend-components.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://probation-frontend-components.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRODUCTION
    AUDIT_ENABLED: "false"

    ALLOCATE_A_PERSON_ON_PROBATION_URL: "https://workforce-management.hmpps.service.justice.gov.uk"
    APPROVED_PREMISES_URL: "https://approved-premises.hmpps.service.justice.gov.uk"
    CONSIDER_A_RECALL_URL: "https://consider-a-recall.hmpps.service.justice.gov.uk"
    MANAGE_PEOPLE_ON_PROBATION_URL: "https://manage-people-on-probation.hmpps.service.justice.gov.uk"
    NDELIUS_URL: "https://ndelius.probation.service.justice.gov.uk"
    OASYS_URL: "https://oasys.service.justice.gov.uk"
    PREPARE_A_CASE_URL: "https://prepare-case-probation.service.justice.gov.uk"
    REFER_AND_MONITOR_URL: "https://refer-monitor-intervention.service.justice.gov.uk"
    TRANSITIONAL_ACCOMODATION_URL: "https://transitional-accommodation.hmpps.service.justice.gov.uk"
    WORKLOAD_MEASUREMENT_TOOL_URL: "https://workload-measurement.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: PROD_ALERTS_SEVERITY_LABEL
