---
# Per environment values which override defaults in hmpps-probation-frontend-component-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: probation-frontend-components-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://probation-frontend-components-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

    ALLOCATE_A_PERSON_ON_PROBATION_URL: "https://workforce-management-dev.hmpps.service.justice.gov.uk"
    APPROVED_PREMISES_URL: "https://approved-premises-dev.hmpps.service.justice.gov.uk"
    CONSIDER_A_RECALL_URL: "https://consider-a-recall-dev.hmpps.service.justice.gov.uk"
    MANAGE_PEOPLE_ON_PROBATION_URL: "https://manage-people-on-probation-dev.hmpps.service.justice.gov.uk"
    NDELIUS_URL: "https://ndelius.test.probation.service.justice.gov.uk"
    OASYS_URL: "https://t2.oasys.service.justice.gov.uk"
    PREPARE_A_CASE_URL: "https://prepare-a-case-dev.apps.live-1.cloud-platform.service.justice.gov.uk"
    REFER_AND_MONITOR_URL: "https://hmpps-interventions-ui-dev.apps.live-1.cloud-platform.service.justice.gov.uk"
    TRANSITIONAL_ACCOMODATION_URL: "https://transitional-accommodation-dev.hmpps.service.justice.gov.uk"
    WORKLOAD_MEASUREMENT_TOOL_URL: "https://workload-measurement-dev.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
