---
# Per environment values which override defaults in hmpps-probation-frontend-component-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: probation-frontend-components-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://probation-frontend-components-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
