name: Deploy to environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - dev
          - preprod
          - prod
        default: 'dev'
      version:
        description: version to be deployed to the environment - must already exist.
        required: true
        default: ''
        type: string

permissions:
  contents: read

jobs:
  helm_lint:
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@8d9c52e65720e36d445d9611f68ca4afd8494526 # v2
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
  deploy_env:
    name: Deploy to environment
    needs:
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@e7db1568006ed68b8238ec1ded2a6c175d6b78a6 # v2
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      app_version: ${{ inputs.version }}
