name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "11 4 * * MON-FRI" # Every weekday
jobs:
  security-veracode-pipeline-scan:
    name: Project security veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@1cd277cf487926d2f86fa68c87049e62a461d55e # v2
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
